# Generated by Django 2.1 on 2018-08-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20180829_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
