# Generated by Django 2.0.5 on 2018-08-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_link_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
