# Generated by Django 2.1 on 2018-09-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_link_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
